### ISSUE TITLE
Validate required fields for the notifier options

### ISSUE THREAD

**Issue by iaguirre88** [wyeworks/boom#17]
We should warn the user that when the library is missconfigured

**Comment by sevgit** [comment]
Hey @iaguirre88 , I'll try to tackle this one if no one is already on it!

How do you see this working? Would it be agnostic to the current notifiers or should we validate the config based on the selected notifiers?

I created the following draft PR so we can nail down the requirements: https://github.com/wyeworks/boom/pull/22

**Comment by iaguirre88** [comment]
First of all, thanks for working on this ❤️ 

> How do you see this working? Would it be agnostic to the current notifiers or should we validate the config based on the selected notifiers?

I imagine it would be a combination of both, but maybe the tricky part about validating every required option per notifier is that it cannot be done in compilation time (not sure about this though 🙄 ). 

So, in that case, I would log a warning saying, for example, that the notification couldn't be sent because the webhook notifier is missing the URL (or something like that). In my opinion, each notifier should be responsible for checking its requiered params.

Also, we need to consider that the user can define a list of notifiers

Let me know what do you think or if you have any questions
