### ISSUE TITLE
Include custom data in the notification

### ISSUE THREAD

**Issue by iaguirre88** [wyeworks/boom#19]
Provide a way to attach custom data in the notification such as the current user.

**Dev notes**
Maybe we can get that info from the assigns in the connection like this`current_user = conn.assigns[:current_user]`

**Comment by brunvez** [comment]
Idea: we could allow users to add a function in the config to extract that data. The function could receive a `%Plug.Conn{}` and return a map/keyword list (a map would be easier to serialize).

**Comment by dnsbty** [comment]
Would it make sense to just include the logger metadata from the process dictionary?

**Comment by iaguirre88** [comment]
> Would it make sense to just include the logger metadata from the process dictionary?

@dnsbty Just in case, we are not using Logger to send the exception information to the notifiers but if there's a way to extract the logger metadata so we can send it to the notifier I don't see why not.

Let me know if anything of what I've just said doesn't make any sense 😅

**Comment by dnsbty** [comment]
Yeah, Logger metadata is stored in the process dictionary. You should be able to access it anywhere like this:

```elixir
:logger.get_process_metadata()
```
