### ISSUE TITLE
Emails should be delivered in background

### ISSUE THREAD

**Issue by smartinez87** [wyeworks/boom#25]
Based on [this](https://github.com/wyeworks/boom/blob/master/lib/boom_notifier/mail_notifier.ex#L47) line, emails seem to be delivered during the cycle of a request.

This means that if an exception occurs, a significant delay will take place while the notification is being sent. Furthermore, if someone hits an exception multiple times there's the possibility of suffering a DDoS while all the emails are being sent.

A suggestion could be sending emails in background, using Bamboo's `deliver_later` method rather than `deliver_now`

**Comment by iaguirre88** [comment]
Nice catch! I hope #26 fixes it
