### ISSUE TITLE
An error occurred when sending a notification

### ISSUE THREAD

**Issue by santoshturamari** [wyeworks/boom#31]
Hi ,

I have installed the boom notifier and it works fine in my local. But in cloud with production mode I am getting file not found error.
An error occurred when sending a notification: ** (File.Error) could not read file "/app/deps/boom_notifier/lib/boom_notifier/mail_notifier/templates/email_body.html.eex": no such file or directory in File.read!/1
Not sure if its the permission issue. Can you please confirm where I am missing.

@spastorino  @joseicosta  @jmbejar 
TIA.

**Comment by iaguirre88** [comment]
Hi, I've noticed you closed the issue but I'd like to confirm whether you were able to fix it. Otherwise, I'm more than happy to help

**Comment by santoshturamari** [comment]
Thanks for the reply.
I observed that the deps folders are not pushed to github. Hence it is unable to find the email template.
Probably I need to make it as local dependency and try to push it. But I need ot explore that option.

**Comment by cedricPoncot** [comment]
Hi, i'm in the same situation. 
Can i know how have you fixed it? :)

**Comment by iaguirre88** [comment]
We'll take a look into it
