### ISSUE TITLE
Fails if stacktrace entry doesn’t contain file and line info

### ISSUE THREAD

**Issue by kerryb** [wyeworks/boom#46]
For example, if the exception is caused by trying to access a field on a variable that’s expected to be a struct but is actually `nil`, then the first stacktrace entry will be `{nil, :some_field, [], []}`. This causes `BoomNotifier.MailNotifier.HTMLContent.entry_to_map/1` to fail with a `MatchError`.

**Comment by kerryb** [comment]
Thanks for the quick fix!

**Comment by iaguirre88** [comment]
I'll try to publish a new version today. Thanks @mcass19 for the fix ❤️
