### ISSUE TITLE
Error in production with release. "(File.Error) could not read file "

### ISSUE THREAD

**Issue by cedricPoncot** [wyeworks/boom#48]
Hi, I'm trying to use BoomNotifier but i got this error when the mail should be deliver.
Here is the error message : 

** (File.Error) could not read file "/home/build/tmp/deps/boom_notifier/lib/boom_notifier/mail_notifier/templates/email_body.html.eex": no such file or directory
    (elixir 1.11.4) lib/file.ex:355: File.read!/1
    (eex 1.11.4) lib/eex.ex:192: EEx.compile_file/2
    (eex 1.11.4) lib/eex.ex:228: EEx.eval_file/3
    (boom_notifier 0.4.0) lib/boom_notifier/mail_notifier.ex:53: BoomNotifier.MailNotifier.notify/2

This error happen in production.
Thanks :)

**Comment by iaguirre88** [comment]
Thanks @cedricPoncot for reporting this bug. We'll take a look into it

**Comment by cedricPoncot** [comment]
Thanks, if you need some additionnal information just tell me

**Comment by grzuy** [comment]
Hi @cedricPoncot, are you using self-contained release with mix release or distillery?

**Comment by cedricPoncot** [comment]
Hi, yes i'm using mix release for production
