### ISSUE TITLE
Proposal: Improve styling of HTML emails

### ISSUE THREAD

**Issue by nicolasferraro** [wyeworks/boom#73]
## Reasoning

As of now HTML emails are rather crude, they are almost indistinguishable from the text version which kind of defeats the point of having two separate versions. While I'm not expecting something fancy, I think a bit of css can go a long way in improving them.

I propose something like the attached image presents, that while still being rudimentary, is more functional since the content sections can be identified clearly. Thoughts?

![image](https://user-images.githubusercontent.com/19378450/146818718-fffcbb62-c296-4084-a31f-40f44e8a43ea.png)

**Comment by iaguirre88** [comment]
It looks beautiful 😍 
Since you have an actual proposal let's close #18 and keep this open

**Comment by nicolasferraro** [comment]
Oh I had missed the other issue!
